apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sap-classes-ingress
  namespace: sap-classes
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: sap-classes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sap-classes
                port:
                  number: 80

